### ISSUE TITLE
(v11) r.evaluateSync is not a function

### ISSUE THREAD

**Issue by serbandr** [EndlesNights/parallax-tiles#1]
Using the v11 version of Parallax Tiles, whenever I try to use a function in the Parallax Factor (like the recommended @elevation * 0.1, though elevation doesn't seem to be a thing in v11 so I tried @flags.levels.rangeTop too) the parallax effect doesn't work at all and the console is flooded with errors saying "r.evaluateSync is not a function" every time I move the canvas. Perhaps this is a v11 specific bug?

**Comment by EndlesNights** [comment]
That is a v11 specific bug, as synchronous roll functions where changes from v11 to v12. I have fixed the issue and added proper backwards support for v11. Hope you enjoy!
